# Use Node 18 base image
FROM node:alpine3.21

# Set working directory inside container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json if available
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY . .

# Expose backend port
EXPOSE 5003

# Command to run the app
CMD ["npm", "start"]
